# Generated by Django 2.2.3 on 2019-07-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('trainer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('mobile_number', models.CharField(max_length=10, unique=True, verbose_name='Mobile Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('dob', models.DateField(default='dd/mm/yyyy')),
                ('batch', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], default='morning', max_length=30)),
                ('photo', models.FileField(blank=True, upload_to='trainer/')),
                ('stop', models.IntegerField(blank=True, choices=[(0, 'Start'), (1, 'Stop')], default=0, verbose_name='Status')),
            ],
        ),
    ]
